### ISSUE TITLE
Unsupported by Thunderbird Beta 64 .0b1

### ISSUE THREAD

**Issue by RogueScholar** [jikamens/enhanced-priority-display#2]
The way they chew through major release numbers I say push it to MaxVersion=70.* this time and buy yourself a couple months before it needs another version pump release. With any luck they'll have come to a concrete decision on the structure of the new add-on framework by then ;)

I really do love the add-on, it completely rectifies one of the more glaring UI deficits that TB has had since the Nutscrape days.

**Comment by jikquantopian** [comment]
It is unfortunately not as simple as simply bumping compatibility.

The Thunderbird devs still haven't fully nailed down how add-ons like mine are going to continue to work after Thunderbird 60. I'm waiting until the dust settles before attempting to port my add-on to newer Thunderbird releases. See https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63.
